### ISSUE TITLE
otel2influx: configurable span "dimensions"

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb-observability#251]
Currently, spans are stored with most attributes converted to a single JSON blob, then stored as one field named `attributes`. Let's improve this by allowing the user to select attribute keys ("dimensions") they would like to be used as InfluxDB tags, and let the rest remain in the `attribute` field.
```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb-observability/pull/253
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23230
- [ ] https://github.com/influxdata/telegraf/pull/13404
```
