### ISSUE TITLE
Write payloads too large

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb-observability#262]
InfluxDB often responds to exporter write requests with `413 Request Entity Too Large` because the line protocol payload is too large. (The otelcol batch processor can be used to limit batch size, but not in terms of bytes out put to InfluxDB.)

To fix this, the influxdbexporter should self-limit based on both bytes and lines of line protocol, defaulting to [the documented suggested limits](https://docs.influxdata.com/influxdb/cloud-serverless/write-data/best-practices/optimize-writes/#batch-writes) of 10,000 lines and 10MB. The service hard limit is 50MB [as documented here](https://docs.influxdata.com/influxdb/cloud-serverless/api/#operation/PostWrite).
```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/influxdb-observability/pull/263
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24001
- [ ] https://github.com/influxdata/telegraf/pull/13559
```
